blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://dsc.gg/bigfoot
    about: Join our discord server, we are trying to get to 500 members by the end of the year!
     - name: Website
    url: https://bgs.pages.dev/g/bgs
    about: Go to our website!
